local mod_path = minetest.get_modpath("automobiles")
dofile(mod_path .. "/common.lua")
dofile(mod_path .. "/car.lua")
dofile(mod_path .. "/pickup.lua")
dofile(mod_path .. "/suv.lua")
dofile(mod_path .. "/config.lua")